title: Hartaj Oberoi
description: Certified AWS Cloud Practitioner | Professional Scrum Master (PSM I) | Master’s in Information Technology & Analytics (Rutgers)
show_downloads: false
theme: jekyll-theme-cayman
